### PR TITLE
Fix-Styles specific to mobile view list items #104

### PR DESCRIPTION
**Pull request by jamie-codes**

### CODE REVIEW

**Comment by JohnAllen** [comment]
Thanks @jamie-codes. Not sure if you need to mark you work as submitted in Gitcoin -- think you do.  Going to accept this one once you do.

**Comment by JohnAllen** [comment]
@jamie-codes Here's where you can click "Submit work" FYI.

https://gitcoin.co/funding/details?url=https://github.com/Distense/distense-ui/issues/104

**Comment by jamie-codes** [comment]
I submitted work. Thanks @JohnAllen!

**Comment by JohnAllen** [comment]
I think you have to do something else @jamie-codes.  It should say so and so submitted work here in this issue.
screen shot 2018-02-20 at 2 00 50 pm

**Comment by jamie-codes** [comment]
@JohnAllen It's showing up now. 
image

**Pull request merged**
