### PR TITLE
Made the FAQs page

### PR DESCRIPTION
**Pull request by tanmayanand44**
Completed the issue #95.
faqs

### CODE REVIEW

**Comment by tanmayanand44** [comment]
@JohnAllen Sir,please review.I have made a basic FAQs page.Do suggest for changes,if any 😄 .

**Comment by JohnAllen** [comment]
Very cool @tanmayanand44!

- Let's move the FAQ link to the footer instead
- Let's remove the unused, imported variables from `faq.js` (these will show up as you run the app)
- Let's capitalize `faq.js`
- Remove the accidentally committed `.faq.js.swp` file

And that will be it -- thanks again! I may make some further modifications over time.

**Comment by tanmayanand44** [comment]
@JohnAllen Ok sure.Will make the changes soon.

**Comment by tanmayanand44** [comment]
@JohnAllen Should I move the faq link to list containing slack invite,email,etc.

**Comment by JohnAllen** [comment]
Good question.  Let's put it in the footer of the app, next to parameters and yes in the main footer in Home as well.

**Pull request closed without merging**
