### PR TITLE
Added PageTitling component to Events page

### PR DESCRIPTION
**Pull request by vikaskyadav**
I think this looks good. Please review once, I am not sure what I committed in last few days.

### CODE REVIEW

**Comment by JohnAllen** [comment]
Would you mind updating the failing test.  You can see what's going on if you click `Details` above.  It's a single number that needs to be changed, so NBD.  Thanks!

**Comment by vikaskyadav** [comment]
Let me have a look at it.

**Comment by vikaskyadav** [comment]
That test is looking for atleast one List component which I have replaced with Grid. I think Grid serves our purpose, I have updated the test file also.

**Comment by vikaskyadav** [comment]
I don't understand the reason. Can I pull another request?

**Comment by JohnAllen** [comment]
These are the errors: ```
./src/components/common/EventItem.js
  Line 2:  'Link' is defined but never used  no-unused-vars
  Line 3:  'List' is defined but never used  no-unused-vars
./src/pages/Events.js
  Line 2:  'List' is defined but never used     no-unused-vars
  Line 3:  'Dimmer' is defined but never used   no-unused-vars
  Line 3:  'Loader' is defined but never used   no-unused-vars
  Line 3:  'Image' is defined but never used    no-unused-vars
  Line 3:  'Segment' is defined but never used  no-unused-vars
  Line 4:  'Icon' is defined but never used     no-unused-vars
```

Basically these are imported but not used, so just removing the imports will fix these errors.

**Comment by vikaskyadav** [comment]
ok. working on linting errors.

**Comment by JohnAllen** [comment]
We can also do:

`import { Card, Grid } from 'react-semantic-ui'`

**Comment by JohnAllen** [comment]
Also here: https://github.com/vikaskyadav/distense-ui/blob/f2d91b855ba2655b314582ae4680c530d5199132/src/pages/Events.js

**Comment by JohnAllen** [comment]
Please create a GitCoin submission @vikaskyadav

**Comment by ctrlaltvikas** [comment]
That  transaction is showing some warning like this:

Transaction Error. Exception thrown in contract code. Insufficient balance
for transactionGas limit set dangerously high. Approving this transaction
is likely to fail.

What to do in this case?

**Pull request merged**
