### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by JohnAllen**

### CODE REVIEW

**Comment by JohnAllen** [comment]
@Atul9 What do you think about this issue template?  Any thoughts?

**Comment by JohnAllen** [comment]
@tanmayanand44 Appreciate any thoughts.

**Comment by tanmayanand44** [comment]
Issue template may include steps to reproduce the error,what could be done,if one who produces that issue claims it or not.

**Comment by tanmayanand44** [comment]
@JohnAllen Am I right?

**Comment by JohnAllen** [comment]
Yes you’re right.  Was thinking more along the lines of Distense proposals but bugs are also common

**Comment by Atul9** [comment]
How about renaming it to NEW_TASK_TEMPLATE? Is it good if we include this is github wiki?

**Comment by JohnAllen** [comment]
@Atul9 I would rename it but Github actually looks for this filename to populate new issues.

**Comment by JohnAllen** [comment]
Closed this because I want to think about it more -- I create so many issues that this will slow me down.  Not sure, what are your thoughts @Atul9 ?

Also it needs to be simple or people won't create tasks/issues

**Comment by JohnAllen** [comment]
Just wondering what the right approach is

**Comment by JohnAllen** [comment]
Add some.  let me know your thoughts

**Comment by Atul9** [comment]
When I view this file at https://github.com/Distense/distense-ui/blob/44bda547a0f7cd07d5417517143ca7894e20aa69/ISSUE_TEMPLATE.md 
It looks like `Operating System. OS:` are on the same line. I think we should put `OS:` on the next line as others like --
```
Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System. 

OS:

Browser and version:
```

**Comment by JohnAllen** [comment]
@Atul9 will fix

**Pull request merged**
