### PR TITLE
DID percentage reformated

### PR DESCRIPTION
**Pull request by ckhatri**
Heyo! 

Saw this on gitcoin https://gitcoin.co/funding/details?url=https://github.com/Distense/distense-ui/issues/181

I assume I claim it after the PR gets pulled?

### CODE REVIEW

**Comment by tanmayanand44** [comment]
@ckhatri It will show 0.02 as 2% which is wrong.

**Comment by ckhatri** [comment]
@tanmayanand44 I think if we did get 0.02% currently it would be the decimal value 0.0002 which would cut off and be 0% shown. Which still is an issue! 

Now what happens is we shift it over two decimals by multiplying by 100 then clip the number of decimals to two digits.

For example 12/10000 will show 
newdid

10/100 will show 
newdid2

**Comment by JohnAllen** [comment]
This is what I got for 85% ownership when making this task/issue:

screen shot 2018-02-17 at 1 51 03 pm

There I owned 85/100, so should be 85%, not 0.85%, just for clarity

**Comment by ckhatri** [comment]
Weird, this is what I got after a fresh build. Also doing 84/100.

screen shot 2018-02-17 at 3 56 20 pm

**Pull request closed without merging**
