### PR TITLE
Added Popups

### PR DESCRIPTION
**Pull request by tanmayanand44**
Done #109.
popup

### CODE REVIEW

**Comment by tanmayanand44** [comment]
@JohnAllen Please review.

**Comment by JohnAllen** [comment]
Thanks @tanmayanand44. Let me think about these a bit more and make sure we have them right.

**Comment by tanmayanand44** [comment]
@JohnAllen A final review would be appreciated. :smiley:

**Comment by tanmayanand44** [comment]
@JohnAllen It didn't work?

**Pull request closed without merging**
