### PR TITLE
Add percent DID ownership to footer

### PR DESCRIPTION
**Pull request by KennethAshley**
# Why? 

We want to add percent did ownership to NumberDIDOwned component in footer.

# What Changed?

We needed to pull in `totalDID` into the now `DidOwnership` component.

### Refs
#172

### CODE REVIEW

**Comment by KennethAshley** [comment]
@JohnAllen No problem! I'll make the changes!

**Comment by KennethAshley** [comment]
@JohnAllen let me know what you think!

**Comment by JohnAllen** [comment]
@KennethAshley Would you mind giving me write access to your fork of this?
  See how to: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

Going to make a couple changes then merge!

**Comment by JohnAllen** [comment]
@KennethAshley You could also simply change the contents of that file and commit to this to save us all time and can move on to the next one 👍 :

```
import React, { Component } from 'react'
import { Menu } from 'semantic-ui-react'
import { connect } from 'react-redux'

import { fetchTotalSupplyDID } from '../../actions/status'
import { getTotalSupplyDID } from '../../reducers/status'

class DIDOwnership extends Component {
  componentDidMount() {
    this.props.fetchTotalSupplyDID()
  }

  componentWillUpdate(nextProps) {
    return (
      this.props.numDID !== nextProps.numDID ||
      this.props.totalSupplyDid !== nextProps.totalSupplyDid
    )
  }

  render() {
    const { numDID, totalSupplyDid } = this.props

    let pctDID = (numDID / totalSupplyDid).toFixed(2)
    pctDID = isNaN(pctDID) ? 0 : pctDID

    return (
      <Menu.Item title="The number of and percentage of total DID the current account owns">
        DID owned: {numDID} ({pctDID}%)
      </Menu.Item>
    )
  }
}

const mapStateToProps = state => ({
  numDID: state.user.user.numDID,
  totalSupplyDid: getTotalSupplyDID(state)
})

const mapDispatchToProps = dispatch => ({
  fetchTotalSupplyDID: () => dispatch(fetchTotalSupplyDID())
})

export default connect(mapStateToProps, mapDispatchToProps)(DIDOwnership)
```

**Comment by KennethAshley** [comment]
@JohnAllen I'll do that. I also messaged you on Gitcoin's slack.

**Pull request merged**
